/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ondecomi.view;
import dao.HamburgerDao;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import ondecomi.model.Hamburgueria;
/**
 *
 * @author Luan Amor
 */
public class NovaHam extends javax.swing.JFrame {
    HamburgerDao dao = new HamburgerDao();
    private int id;
    private String nomeAvaliador;
    private String end = "Endereço";
    private String nome = "Nome";
    private float preco = 0;
    private float ambiente = 0;
    private float atendimento = 0;
    private float hamburger = 0;
    private float acompanhamento = 0;
    /**
     * Creates new form NovaHam
     */
    public NovaHam() {
        initComponents();
        setIcon();
    }
    
    public void recebeId(int id, String nome){
        this.nomeAvaliador = nome;
        this.id = id;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnSalvarHam = new javax.swing.JButton();
        txtEndHam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Notas1a9 = new javax.swing.JLabel();
        notaPrecoHam = new javax.swing.JFormattedTextField();
        notaAmbienteHam = new javax.swing.JFormattedTextField();
        notaAtendimentoHam = new javax.swing.JFormattedTextField();
        notaHamburgerHam = new javax.swing.JFormattedTextField();
        notaAcompanhamentosHam = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        lbend = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notaGeralHam = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnVoltarHam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeHam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nova Hamburgueria");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalvarHam.setBackground(new Color(0,0,0,0));
        btnSalvarHam.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnSalvarHam.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarHam.setText("Salvar");
        btnSalvarHam.setBorder(null);
        btnSalvarHam.setBorderPainted(false);
        btnSalvarHam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarHam.setFocusPainted(false);
        btnSalvarHam.setFocusable(false);
        btnSalvarHam.setOpaque(false);
        btnSalvarHam.setRequestFocusEnabled(false);
        btnSalvarHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarHamActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 145, -1));

        txtEndHam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEndHam.setText("Qual o endereço?");
        getContentPane().add(txtEndHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        Notas1a9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Notas1a9.setForeground(new java.awt.Color(255, 255, 255));
        Notas1a9.setText("Notas de 0 a 9:");
        getContentPane().add(Notas1a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        try {
            notaPrecoHam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaPrecoHam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaPrecoHam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaPrecoHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 40, 30));

        try {
            notaAmbienteHam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaAmbienteHam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaAmbienteHam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        notaAmbienteHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaAmbienteHamActionPerformed(evt);
            }
        });
        getContentPane().add(notaAmbienteHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 190, 40, 30));

        try {
            notaAtendimentoHam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaAtendimentoHam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaAtendimentoHam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaAtendimentoHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 230, 40, 30));

        try {
            notaHamburgerHam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaHamburgerHam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaHamburgerHam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaHamburgerHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 270, 40, 30));

        try {
            notaAcompanhamentosHam.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaAcompanhamentosHam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaAcompanhamentosHam.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaAcompanhamentosHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 310, 40, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Atendimento......................................");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbend.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbend.setForeground(new java.awt.Color(255, 255, 255));
        lbend.setText("Endereço:");
        getContentPane().add(lbend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Nota Geral");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 356, -1, 30));

        notaGeralHam.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        notaGeralHam.setText("0.0");
        getContentPane().add(notaGeralHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, 20));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Preço..................................................");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hamburguer.......................................");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnVoltarHam.setBackground(new Color(0,0,0,0));
        btnVoltarHam.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        btnVoltarHam.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarHam.setText("Voltar");
        btnVoltarHam.setBorder(null);
        btnVoltarHam.setBorderPainted(false);
        btnVoltarHam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarHam.setFocusPainted(false);
        btnVoltarHam.setFocusable(false);
        btnVoltarHam.setOpaque(false);
        btnVoltarHam.setRequestFocusEnabled(false);
        btnVoltarHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarHamActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 145, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ambiente............................................");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Acompanhamentos............................");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtNomeHam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeHam.setText("Informe o nome da Hamburgueria?");
        txtNomeHam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeHamActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 280, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ondecomi/view/Imagens/novaHamb.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 0, 670, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarHamActionPerformed
        //Instancioando Hamburgueria
        end = txtEndHam.getText();
        nome = txtNomeHam.getText();
        preco = Float.parseFloat(notaPrecoHam.getText());
        ambiente = Float.parseFloat(notaAmbienteHam.getText());
        atendimento = Float.parseFloat(notaAtendimentoHam.getText());
        hamburger = Float.parseFloat(notaHamburgerHam.getText());
        acompanhamento = Float.parseFloat(notaAcompanhamentosHam.getText());
        Hamburgueria newHam = new Hamburgueria(nome, end, preco, ambiente, atendimento, hamburger, acompanhamento);
        //Preenchendo tabelas Hamburgueria e avalia_hamburger
        dao.addHamburgueria(newHam);
        dao.addAvaliaHam(id);
        // Geral
        float a1 = (preco + ambiente + atendimento + hamburger + acompanhamento)/5;
        notaGeralHam.setText(Float.toString(a1));
        JOptionPane.showMessageDialog(null, "Nova Hamburgueria adicionada!");
        // Fechando a tela
        JHamburguerias jhams = new JHamburguerias();
        jhams.setVisible(true);
        jhams.recebeId(Integer.toString(id), nomeAvaliador);
        dispose();
    }//GEN-LAST:event_btnSalvarHamActionPerformed

    private void btnVoltarHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarHamActionPerformed
        JHamburguerias jhams = new JHamburguerias();
        jhams.setVisible(true);
        jhams.recebeId(Integer.toString(id), nomeAvaliador);
        dispose();
    }//GEN-LAST:event_btnVoltarHamActionPerformed

    private void txtNomeHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeHamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeHamActionPerformed

    private void notaAmbienteHamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaAmbienteHamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notaAmbienteHamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovaHam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovaHam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovaHam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovaHam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaHam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Notas1a9;
    private javax.swing.JButton btnSalvarHam;
    private javax.swing.JButton btnVoltarHam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbend;
    private javax.swing.JFormattedTextField notaAcompanhamentosHam;
    private javax.swing.JFormattedTextField notaAmbienteHam;
    private javax.swing.JFormattedTextField notaAtendimentoHam;
    private javax.swing.JLabel notaGeralHam;
    private javax.swing.JFormattedTextField notaHamburgerHam;
    private javax.swing.JFormattedTextField notaPrecoHam;
    private javax.swing.JTextField txtEndHam;
    private javax.swing.JTextField txtNomeHam;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("food.png")));
    }
}
