/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ondecomi.view;
import dao.SushiDao;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import ondecomi.model.Japones;
/**
 *
 * @author Luan Amor
 */
public class NovoJapones extends javax.swing.JFrame {
    SushiDao dao = new SushiDao();
    private int id;
    private String nomeAvaliador;
    private String end = "Endereço";
    private String nome = "Nome";
    private float preco = 0;
    private float ambiente = 0;
    private float atendimento = 0;
    private float peixe = 0;
    private float variedades = 0;
    /**
     * Creates new form NovoJapones
     */
    public NovoJapones() {
        initComponents();
        setIcon();
    }
    
    public void recebeId(int id, String nome){
        this.nomeAvaliador = nome;
        this.id = id;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        notaGeralJapones = new javax.swing.JLabel();
        notaPrecoJapones = new javax.swing.JFormattedTextField();
        notaAmbienteJapones = new javax.swing.JFormattedTextField();
        notaAtendimentoJapones = new javax.swing.JFormattedTextField();
        notaPFrescoJapones = new javax.swing.JFormattedTextField();
        notaVariedadesJapones = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVoltarJapones = new javax.swing.JButton();
        txtNomeJapones = new javax.swing.JTextField();
        btnSalvarJapones = new javax.swing.JButton();
        txtEndJapones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbend = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novo restaurante japonês");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nota Geral");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Atendimento............................");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        notaGeralJapones.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        notaGeralJapones.setForeground(new java.awt.Color(255, 255, 255));
        notaGeralJapones.setText("0.0");
        getContentPane().add(notaGeralJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 30));

        try {
            notaPrecoJapones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaPrecoJapones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaPrecoJapones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaPrecoJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 150, 40, 30));

        try {
            notaAmbienteJapones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaAmbienteJapones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaAmbienteJapones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaAmbienteJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 190, 40, 30));

        try {
            notaAtendimentoJapones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaAtendimentoJapones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaAtendimentoJapones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaAtendimentoJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 230, 40, 30));

        try {
            notaPFrescoJapones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaPFrescoJapones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaPFrescoJapones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaPFrescoJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 270, 40, 30));

        try {
            notaVariedadesJapones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        notaVariedadesJapones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        notaVariedadesJapones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(notaVariedadesJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 310, 40, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nostas de 0 a 9:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Peixe Fresco.............................");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Variedades................................");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        btnVoltarJapones.setBackground(new Color(0,0,0,0));
        btnVoltarJapones.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        btnVoltarJapones.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarJapones.setText("Voltar");
        btnVoltarJapones.setBorder(null);
        btnVoltarJapones.setBorderPainted(false);
        btnVoltarJapones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltarJapones.setFocusPainted(false);
        btnVoltarJapones.setFocusable(false);
        btnVoltarJapones.setOpaque(false);
        btnVoltarJapones.setRequestFocusEnabled(false);
        btnVoltarJapones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarJaponesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltarJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 145, -1));

        txtNomeJapones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeJapones.setText("Informe o nome do Restaurante?");
        txtNomeJapones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeJaponesActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, 30));

        btnSalvarJapones.setBackground(new Color(0,0,0,0));
        btnSalvarJapones.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        btnSalvarJapones.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarJapones.setText("Salvar");
        btnSalvarJapones.setBorder(null);
        btnSalvarJapones.setBorderPainted(false);
        btnSalvarJapones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarJapones.setFocusPainted(false);
        btnSalvarJapones.setFocusable(false);
        btnSalvarJapones.setOpaque(false);
        btnSalvarJapones.setRequestFocusEnabled(false);
        btnSalvarJapones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarJaponesActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvarJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 145, -1));

        txtEndJapones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEndJapones.setText("Qual o endereço?");
        getContentPane().add(txtEndJapones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 270, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        lbend.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbend.setForeground(new java.awt.Color(255, 255, 255));
        lbend.setText("Endereço:");
        getContentPane().add(lbend, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Preço.......................................");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ambiente..................................");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ondecomi/view/Imagens/novoJapo.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 0, 630, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarJaponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarJaponesActionPerformed
        JJapones japas = new JJapones();
        japas.setVisible(true);
        japas.recebeId(Integer.toString(id), nomeAvaliador);
        dispose();
    }//GEN-LAST:event_btnVoltarJaponesActionPerformed

    private void btnSalvarJaponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarJaponesActionPerformed
        //Instanciando Japones
        end = txtEndJapones.getText();
        nome = txtNomeJapones.getText();
        preco = Float.parseFloat(notaPrecoJapones.getText());
        ambiente = Float.parseFloat(notaAmbienteJapones.getText());
        atendimento = Float.parseFloat(notaAtendimentoJapones.getText());
        peixe = Float.parseFloat(notaPFrescoJapones.getText());
        variedades = Float.parseFloat(notaVariedadesJapones.getText());
        Japones newJapones = new Japones(nome, end, preco, ambiente, atendimento, peixe, variedades);
        //Preenchendo banco de dados tabelas: Japones e avalia_sushi
        dao.addJapones(newJapones);
        dao.addAvaliaJapones(id);
        //NotaGeral
        float a1 = (preco + ambiente + atendimento + peixe + variedades)/5;
        notaGeralJapones.setText(Float.toString(a1));
        JOptionPane.showMessageDialog(null, "Novo restaurante Japonês adicionado!");
        //Fechando a tela
        JJapones japas = new JJapones();
        japas.setVisible(true);
        japas.recebeId(Integer.toString(id), nomeAvaliador);
        dispose();


    }//GEN-LAST:event_btnSalvarJaponesActionPerformed

    private void txtNomeJaponesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeJaponesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeJaponesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJapones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJapones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJapones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJapones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJapones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarJapones;
    private javax.swing.JButton btnVoltarJapones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbend;
    private javax.swing.JFormattedTextField notaAmbienteJapones;
    private javax.swing.JFormattedTextField notaAtendimentoJapones;
    private javax.swing.JLabel notaGeralJapones;
    private javax.swing.JFormattedTextField notaPFrescoJapones;
    private javax.swing.JFormattedTextField notaPrecoJapones;
    private javax.swing.JFormattedTextField notaVariedadesJapones;
    private javax.swing.JTextField txtEndJapones;
    private javax.swing.JTextField txtNomeJapones;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("food.png")));
    }
}
