/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ondecomi.view;
import dao.AvaliadorDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ondecomi.model.*;
import Imagens.*;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Luan Amor
 */
public class TelaLogin extends javax.swing.JFrame {
    Avaliadores enviarDados;
   // Avaliador ava;
    private String teste;
    ArrayList<Avaliador> avaliadores = new ArrayList();
    AvaliadorDao novo = new AvaliadorDao();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAvaliadores = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        areaTrb2 = new javax.swing.JDesktopPane();
        btnSelecionaAvaliador1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNovoAvaliador1 = new javax.swing.JButton();
        btnSelecionaAvaliador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNovoAvaliador = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        btnAvaliadores.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnAvaliadores.setText("Avaliadores");

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Acesso");
        jFrame1.setResizable(false);

        btnSelecionaAvaliador1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnSelecionaAvaliador1.setText("Avaliador");
        btnSelecionaAvaliador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaAvaliador1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("High Tower Text", 1, 48)); // NOI18N
        jLabel3.setText("Onde Comi?");

        btnNovoAvaliador1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        btnNovoAvaliador1.setText("Novo Avaliador");
        btnNovoAvaliador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAvaliador1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout areaTrb2Layout = new javax.swing.GroupLayout(areaTrb2);
        areaTrb2.setLayout(areaTrb2Layout);
        areaTrb2Layout.setHorizontalGroup(
            areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaTrb2Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(areaTrb2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecionaAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        areaTrb2Layout.setVerticalGroup(
            areaTrb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTrb2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addGap(93, 93, 93)
                .addComponent(btnSelecionaAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnNovoAvaliador1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        areaTrb2.setLayer(btnSelecionaAvaliador1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        areaTrb2.setLayer(btnNovoAvaliador1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addComponent(areaTrb2)
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrb2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelecionaAvaliador.setBackground(new Color(0,0,0,0));
        btnSelecionaAvaliador.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        btnSelecionaAvaliador.setForeground(new java.awt.Color(255, 255, 255));
        btnSelecionaAvaliador.setText("Avaliador");
        btnSelecionaAvaliador.setBorder(null);
        btnSelecionaAvaliador.setBorderPainted(false);
        btnSelecionaAvaliador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelecionaAvaliador.setFocusPainted(false);
        btnSelecionaAvaliador.setFocusable(false);
        btnSelecionaAvaliador.setOpaque(false);
        btnSelecionaAvaliador.setRequestFocusEnabled(false);
        btnSelecionaAvaliador.setRolloverEnabled(false);
        btnSelecionaAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaAvaliadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelecionaAvaliador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 330, 60));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Onde Comi?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 330, -1));

        btnNovoAvaliador.setBackground(new Color(0,0,0,0)
        );
        btnNovoAvaliador.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        btnNovoAvaliador.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoAvaliador.setText("Novo Avaliador");
        btnNovoAvaliador.setBorder(null);
        btnNovoAvaliador.setBorderPainted(false);
        btnNovoAvaliador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoAvaliador.setFocusPainted(false);
        btnNovoAvaliador.setFocusable(false);
        btnNovoAvaliador.setOpaque(false);
        btnNovoAvaliador.setRequestFocusEnabled(false);
        btnNovoAvaliador.setRolloverEnabled(false);
        btnNovoAvaliador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAvaliadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoAvaliador, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 330, 60));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ondecomi/view/Imagens/login.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAvaliadorActionPerformed
        AvaliadorDao n = new AvaliadorDao();
        String nome = JOptionPane.showInputDialog("Informe o nome do Avaliador");
        if(nome.equals(null) || nome.equals("") || nome.equals(" ")){
            JOptionPane.showMessageDialog(null, "Informe um nome para o Avaliador");
        }else{
            Avaliador ava = new Avaliador(nome);
            n.addAvaliador(ava);
            JOptionPane.showMessageDialog(null, "Avaliador "+nome+" adicionado!");
        }
        
    }//GEN-LAST:event_btnNovoAvaliadorActionPerformed

    private void btnSelecionaAvaliadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaAvaliadorActionPerformed
        enviarDados = new Avaliadores();
        enviarDados.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSelecionaAvaliadorActionPerformed

    private void btnSelecionaAvaliador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaAvaliador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelecionaAvaliador1ActionPerformed

    private void btnNovoAvaliador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAvaliador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNovoAvaliador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrb2;
    private javax.swing.JButton btnAvaliadores;
    private javax.swing.JButton btnNovoAvaliador;
    private javax.swing.JButton btnNovoAvaliador1;
    private javax.swing.JButton btnSelecionaAvaliador;
    private javax.swing.JButton btnSelecionaAvaliador1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("food.png")));
    }
}
